# Just need to edit this section now 

substitutions:
  name:                                     # Fill these fields
  friendly_name:                            # Fill these fields
  key: !secret                              # Fill these fields
  ota: !secret                              # Fill these fields
  wifipass: "HAHA2205"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

web_server:

esp32_improv:
  authorizer: none

# Enable Home Assistant API
api:
  encryption:
    key: ${key}

ota:
  - platform: esphome
    password: ${ota}

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ${wifipass}

captive_portal:


switch:
  - platform: gpio
    pin:                                    # Fill Value
    name:                                   # Fill Value
    id: R1
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:

#Right Socket
  - platform: gpio
    name:                                    # Fill Value
    id: S1
    pin:                                     
      number:                                # Fill Value
      inverted: True                         
      mode: 
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S1
            then:
              - switch.turn_on: R1
            else:
              - switch.turn_off: R1
